### ISSUE TITLE
ERROR: Action "init" needs root access

### ISSUE THREAD

**Issue by marktnz1** [waydroid/waydroid.github.io#11]
Recently downloaded, installed can't initialise

$ waydroid init
ERROR: Action "init" needs root access

No solution to problem appears available.

STEPS TAKEN: (from https://docs.waydro.id/usage/install-on-desktops)
sudo apt install curl ca-certificates -y (already installed)
curl https://repo.waydro.id | sudo bash 
waydroid session start
[12:47:52] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
[12:47:52] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
Unlclear what to do, Y does not work
waydroid -h 
waydroid first-launch
Installed GAPPS

ERROR: Action "init" needs root access

**Comment by Quackdoc** [comment]
not the right place to file this, use sudo, also you need to be running a wayland compositor

**Comment by soolo-as** [comment]
Why does waydroid need root access?
